name: gamified
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dart_mappable: ^4.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  hugeicons: ^1.1.1
  smooth_sheets: ^0.15.0
  cached_network_image: ^3.4.1
  confetti: ^0.8.0
  shadcn_ui: ^0.39.7
  drift: ^2.25.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  clarity_flutter: ^1.2.0
  http: ^1.4.0
  flutter_dotenv: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  logger: ^2.6.1
  intl: ^0.20.2
  lottie: ^3.3.1
  motor: ^1.0.0-dev.6
  gaimon: ^1.4.1
  flutter_slidable: ^4.0.1
  drift_flutter: ^0.2.7
  health: ^13.2.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0 # contains Isar Core
  url_launcher: ^6.3.2
  open_settings_plus: ^0.4.0
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  isar_community_generator: ^3.3.0
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome/
    - assets/logo/
    - assets/images/
    - assets/images/workouts/
    - assets/svg/
    - assets/animation/
    - assets/haptics/
    - .env

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
